### ISSUE TITLE
feat: 请求一个revanced cli的修补命令

### ISSUE THREAD

**Issue by gumiling** [BiliRoamingX/BiliRoamingX#144]
### 原因

我使用./gradlew :patches:build编译了一下这个项目，得到了一个大小为812k的补丁包，我不知道流程是否正确，但我随后用java -jar revanced-cli-4.6.0-all.jar patch bilibili-7.70.0.apk --patch-bundle BiliRoamingX-patches-1.19.2.jar这行命令修补时报了很多错，最终得到的APP也是完全无法使用的状态

### 功能简述

希望能够指点一下这两部分使用的命令

### 功能逻辑

无

**Comment by gumiling** [comment]
编译的版本是commit d3c2650

**Comment by zjns** [comment]
`dist` 会在项目根目录 build 文件夹下生成 integrations和 patch。

**Comment by zjns** [comment]
最好用我这个修改版的 [cli](https://github.com/zjns/revanced-cli/releases) `--sign-levels "2,3"` 指定签名级别打包，不然安装后一分钟内回闪退。

**Comment by gumiling** [comment]
> 最好用我这个修改版的 [cli](https://github.com/zjns/revanced-cli/releases) 指定签名级别打包，不然安装后一分钟内回闪退。`--sign-levels "2,3"`

我编译出了一个929k的jar包和一个APP，但是我在修补哔哩哔哩7.70.0时仍然报错，修补出来的app无法使用，我使用的java版本是java17，使用的测试命令是java -jar revanced-cli.jar patch --sign-levels "2,3" -b BiliRoamingX-patches-1.19.2.jar  7.70.0.apk，请问是否有不正确的地方呢？

附上报错内容：
[新建文本文档.txt](https://github.com/BiliRoamingX/BiliRoamingX/files/15050804/default.txt)

**Comment by zjns** [comment]
apk 和 jar 都要用，apk `--merge` jar `--patch-bundle`

**Comment by gumiling** [comment]
> apk 和 jar 都要用，apk `--merge` jar `--patch-bundle`

感谢，我已经成功修补了，还剩唯一的报错，无论加不加--sign-levels "2,3"都如此，询问ai和搜索都没有得到具体的解决方案：
org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$BCKeyStoreException: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(Unknown Source)
        at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1167)
        at app.revanced.library.ApkSigner.newKeyStore(ApkSigner.kt:56)
        at app.revanced.library.ApkUtils.newPrivateKeyCertificatePair(ApkUtils.kt:114)
        at app.revanced.library.ApkUtils.signApk(ApkUtils.kt:168)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:331)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.makePBECipher(Unknown Source)
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$StoreEntry.<init>(Unknown Source)
        ... 15 more

目前我将修补好后没有签名的安装包发送到手机上用mt管理器签v2+v3名，暂时看来可以正常使用，但是我想提问，patches.json有什么作用呢？我在官方文档里也没有看到如何使用的案例

**Comment by zjns** [comment]
没什么用，忽略就行

**Comment by gumiling** [comment]
> 没什么用，忽略就行

好的谢谢

**Comment by gumiling** [comment]
> 没什么用，忽略就行

那么那个报错是我哪里没弄对呢？因为昨晚我还能正常签名不报错，今天就出问题了

**Comment by gumiling** [comment]
> > 没什么用，忽略就行
> 
> 那么那个报错是我哪里没弄对呢？因为昨晚我还能正常签名不报错，今天就出问题了

已解决，修补应用时使用java11即可
