### ISSUE TITLE
閃退

### ISSUE THREAD

**Issue by NeKoOuO** [BiliRoamingX/BiliRoamingX#199]
### 系统版本

MIUI14

### Android 版本

13

### 哔哩哔哩版本

Play 版（国际版）

### 哔哩哔哩版本号

7.40.0

### 问题描述

閃退

### 复现步骤

打開解析服務器要複製網址時卡住後閃退

### 日志

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.ClipDescription.hasMimeType(java.lang.String)' on a null object reference
	at android.widget.TextView.canPasteAsPlainText(Unknown Source:20)
	at android.widget.Editor$TextActionModeCallback.populateMenuWithItems(Unknown Source:176)
	at android.widget.Editor$TextActionModeCallback.onCreateActionMode(Unknown Source:16)
	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onCreateActionMode(Unknown Source:2)
	at com.android.internal.policy.DecorView.startActionMode(Unknown Source:95)
	at com.android.internal.policy.DecorView.startActionModeForChild(Unknown Source:0)
	at android.view.ViewGroup.startActionModeForChild(Unknown Source:45)
	at android.view.ViewGroup.startActionModeForChild(Unknown Source:45)
	at android.view.ViewGroup.startActionModeForChild(Unknown Source:45)
	at android.view.ViewGroup.startActionModeForChild(Unknown Source:45)
	at android.view.ViewGroup.startActionModeForChild(Unknown Source:45)
	at android.view.ViewGroup.startActionModeForChild(Unknown Source:45)
	at android.view.ViewGroup.startActionModeForChild(Unknown Source:45)
	at android.view.View.startActionMode(Unknown Source:8)
	at android.widget.Editor.startActionModeInternal(Unknown Source:42)
	at android.widget.SelectionActionModeHelper.startActionMode(Unknown Source:93)
	at android.widget.SelectionActionModeHelper.startSelectionActionMode(Unknown Source:1)
	at android.widget.SelectionActionModeHelper.lambda$startSelectionActionModeWithSmartSelectAnimation$0$android-widget-SelectionActionModeHelper(Unknown Source:37)
	at android.widget.SelectionActionModeHelper$$ExternalSyntheticLambda9.run(Unknown Source:4)
	at android.widget.SelectionActionModeHelper.startSelectionActionModeWithSmartSelectAnimation(Unknown Source:41)
	at android.widget.SelectionActionModeHelper.$r8$lambda$mMDhXh3JQs_q5UuyTdq2CLenZJk(Unknown Source:0)
	at android.widget.SelectionActionModeHelper$$ExternalSyntheticLambda11.accept(Unknown Source:4)
	at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(Unknown Source:20)
	at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(Unknown Source:2)
	at android.os.AsyncTask.finish(Unknown Source:10)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(Unknown Source:25)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)

**Comment by NeKoOuO** [comment]
搞錯了 已更改

**Comment by zjns** [comment]
这日志跟模块也没关系吧
