### ISSUE TITLE
bug: 编译时遇到错误

### ISSUE THREAD

**Issue by do02fw** [BiliRoamingX/BiliRoamingX#200]
### 系统版本

Windows 11 x64 24H2 26100.268，JDK22 x64，Windows配置16G内存，i3-12100 CPU

### Android 版本

14

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

7.76

### 问题描述

org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$BCKeyStoreException: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(Unknown Source)
        at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1191)
        at app.revanced.library.ApkSigner.newKeyStore(ApkSigner.kt:56)
        at app.revanced.library.ApkUtils.newPrivateKeyCertificatePair(ApkUtils.kt:114)
        at app.revanced.library.ApkUtils.signApk(ApkUtils.kt:168)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:331)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.makePBECipher(Unknown Source)
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$StoreEntry.<init>(Unknown Source)
        ... 15 more

### 复现步骤

执行命令java -jar revanced-cli.jar patch --merge BiliRoamingX-integrations-1.20.3.apk --patch-bundle BiliRoamingX-patches-1.20.3.jar --signing-levels 2,3 iBiliPlayer-bili.apk

### 日志

java -jar revanced-cli.jar patch --merge BiliRoamingX-integrations-1.20.3.apk --patch-bundle BiliRoamingX-patches-1.20.3.jar --signing-levels 2,3 iBiliPlayer-bili.apk
淇℃伅: Loading patches
淇℃伅: Decoding app manifest
淇℃伅: Enable Android debugging excluded
淇℃伅: Change package name excluded
淇℃伅: Remove screenshot restriction excluded
淇℃伅: Remove screen capture restriction excluded
淇℃伅: Spoof Wi-Fi connection excluded
淇℃伅: Export all activities excluded
淇℃伅: Spoof SIM country excluded
淇℃伅: Predictive back gesture excluded
淇℃伅: Setting patch options
淇℃伅: Merging integrations
淇℃伅: Deleting existing temporary files directory
淇℃伅: Decoding resources
淇℃伅: Executing patches
淇℃伅: App icon succeeded
淇℃伅: Append signature info for LSPatch succeeded
淇℃伅: Auto like succeeded
淇℃伅: BL route intercept succeeded
淇℃伅: BiliRoamingX settings entrance succeeded
淇℃伅: Blkv succeeded
淇℃伅: Block thai comment succeeded
淇℃伅: Block up recommend ads succeeded
淇℃伅: Brotli succeeded
淇℃伅: Cache redirect succeeded
淇℃伅: Comment word search url succeeded
淇℃伅: Config succeeded
淇℃伅: Config succeeded
淇℃伅: Copy enhance succeeded
淇℃伅: Crash handler succeeded
淇℃伅: Custom splash succeeded
淇℃伅: Custom theme color succeeded
淇℃伅: Dark switch succeeded
淇℃伅: Default playback speed succeeded
淇℃伅: Disable auto select succeeded
淇℃伅: Disable live room double click succeeded
淇℃伅: Dpi succeeded
淇℃伅: Drawer succeeded
淇℃伅: Fix preference manager succeeded
淇℃伅: Forbid auto subscribe succeeded
淇℃伅: Forbid live room auto float succeeded
淇℃伅: Forbid live room slide left succeeded
淇℃伅: Forbid switch live room succeeded
淇℃伅: Force hardware codec succeeded
淇℃伅: Hide follow button succeeded
淇℃伅: Inject DocumentsProvider succeeded
淇℃伅: Integrations succeeded
淇℃伅: Json succeeded
淇℃伅: Lib bili succeeded
淇℃伅: Long press playback speed succeeded
淇℃伅: Main activity patch succeeded
淇℃伅: Make text selectable succeeded
淇℃伅: Modify modifier succeeded
淇℃伅: Moss succeeded
淇℃伅: Music notification succeeded
淇℃伅: Number format succeeded
淇℃伅: OkHttp succeeded
淇℃伅: Override certificate pinning succeeded
淇℃伅: Override playback speed succeeded
淇℃伅: Pegasus hook succeeded
淇℃伅: Per app language succeeded
淇℃伅: Player gesture detector hook succeeded
淇℃伅: Player toast succeeded
淇℃伅: ProtoBuf print succeeded
淇℃伅: Remove managerSpaceActivity succeeded
淇℃伅: Remove vip section succeeded
淇℃伅: Save comment images succeeded
淇℃伅: Search type succeeded
淇℃伅: Share succeeded
淇℃伅: Splash succeeded
淇℃伅: Subtitle import and save succeeded
淇℃伅: Subtitle import and save button succeeded
淇℃伅: Subtitle style succeeded
淇℃伅: Teenager mode succeeded
淇℃伅: Text fold succeeded
淇℃伅: Toast succeeded
淇℃伅: Trial quality succeeded
淇℃伅: Unlock ProtoBuf succeeded
淇℃伅: Upgrade succeeded
淇℃伅: Video default quality succeeded
淇℃伅: Webview succeeded
淇℃伅: Compiling patched dex files
淇℃伅: Compiled classes.dex
淇℃伅: Compiled classes2.dex
淇℃伅: Compiled classes3.dex
淇℃伅: Compiled classes4.dex
淇℃伅: Compiled classes5.dex
淇℃伅: Compiled classes6.dex
淇℃伅: Compiled classes7.dex
淇℃伅: Compiled classes8.dex
淇℃伅: Compiled classes9.dex
淇℃伅: Compiled classes10.dex
淇℃伅: Compiled classes11.dex
淇℃伅: Compiled classes12.dex
淇℃伅: Compiled classes13.dex
淇℃伅: Compiled classes14.dex
淇℃伅: Compiled classes15.dex
淇℃伅: Compiled classes16.dex
淇℃伅: Compiled classes17.dex
淇℃伅: Compiled classes18.dex
淇℃伅: Compiled classes19.dex
淇℃伅: Compiled classes20.dex
淇℃伅: Compiled classes21.dex
淇℃伅: Compiled classes22.dex
淇℃伅: Compiled classes23.dex
淇℃伅: Compiled classes24.dex
淇℃伅: Compiled classes25.dex
淇℃伅: Compiled classes26.dex
淇℃伅: Compiled classes27.dex
淇℃伅: Compiled classes28.dex
淇℃伅: Compiled classes29.dex
淇℃伅: Compiled classes30.dex
淇℃伅: Compiled classes31.dex
淇℃伅: Compiled classes32.dex
淇℃伅: Compiled classes33.dex
淇℃伅: Compiled classes34.dex
淇℃伅: Compiling modified resources
淇℃伅: Aligning APK
org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$BCKeyStoreException: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(Unknown Source)
        at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1191)
        at app.revanced.library.ApkSigner.newKeyStore(ApkSigner.kt:56)
        at app.revanced.library.ApkUtils.newPrivateKeyCertificatePair(ApkUtils.kt:114)
        at app.revanced.library.ApkUtils.signApk(ApkUtils.kt:168)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:331)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.makePBECipher(Unknown Source)
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$StoreEntry.<init>(Unknown Source)
        ... 15 more

**Comment by zjns** [comment]
自行Google解决
