### ISSUE TITLE
[BUG] Override playback speed failed

### ISSUE THREAD

**Issue by leisurefire** [BiliRoamingX/BiliRoamingX#392]
### 开发环境

OpenJDK

### 操作系统

Windows

### 哔哩哔哩版本

粉版（普通版）

### 哔哩哔哩版本号

8.9.0

### 问题描述

Patch to override playback speed failed.

### 日志

Critical: Override playback speed failed:
app.revanced.patcher.patch.PatchException: Failed to resolve MenuFuncSegmentFingerprint
        at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:25)
        at app.revanced.patches.bilibili.video.player.patch.OverridePlaybackSpeedPatch.execute(OverridePlaybackSpeedPatch.kt:104)
        at app.revanced.patches.bilibili.video.player.patch.OverridePlaybackSpeedPatch.execute(OverridePlaybackSpeedPatch.kt:24)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:173)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:205)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$1$1.invokeSuspend(PatchCommand.kt:313)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:312)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)

**Comment by zjns** [comment]
Use latest ci https://github.com/BiliRoamingX/BiliRoamingX/actions/runs/10380842186.
